[WIP] Position backdrop image/video according to motif area
codevise/pageflow pull request #1582
Opened 2020-10-07 15:21 UTC by tf

**Still contains all commits from #1581**

REDMINE-17865

2020-10-20 13:42 UTC, aviav requested changes
After reading it all, I think there's only one naming issue to discuss. All change requests are probably quickly resolved.

Regarding this review, I didn't try to understand everything really in-depth. Clearing up the necessary context for that would've taken too much time, I think. Instead, I had a good look commit by commit, trying to understand each one on its own and mostly locally, and also looked at the stories. At the end I had a look at the whole review and the PR's code, and removed/adjusted some comments where meaning had emerged from between commits.

If there are undiscovered issues in this code that need fixing, I think all the docs and well-written code will mean that we can find much more easily what needs to be done. I am curious what the users make of this, and how far the heuristics you chose will carry.

For a first iteration in terms of solving backdrop positioning according to motif area, this goes quite far, in a good way

2020-10-21 11:39 UTC, tf commented on entry_types/scrolled/package/spec/editor/models/SectionConfiguration-spec.js
> +      sectionConfiguration.set('backdropVideoMotifArea', motifArea);
We discussed this point and decided to stick with the separate attribute for now.

2020-10-21 11:41 UTC, tf commented on entry_types/scrolled/package/spec/frontend/MotifArea-spec.js
> +    expect(container.firstChild).toHaveStyle('top: 100px');
As discussed offline, this is a sort of idiomatic use case of our testing library - even though using `container` in the first place should be considered a last resort for cases (like this) where none of the available query methods seem applicable.

2020-10-21 11:42 UTC, tf commented on entry_types/scrolled/package/spec/frontend/VideoPlayer-spec.js
> +  it('passes object position based on motif area to media api when fit is cover', () => {
At the moment, object fit is used exclusively for backdrop videos.

2020-10-21 11:44 UTC, tf commented on entry_types/scrolled/package/src/frontend/Image.js
> +           objectPosition: `${cropPositionX}% ${cropPositionY}%`
We decided to stick crop since "shift" would only be somewhat better and not worth the effort of finding all places that would need to be changed.

2020-10-21 13:02 UTC, merged